// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Evaluate(arg1:string):Promise<any>;

export function OpenFile():Promise<any>;

export function SaveFile(arg1:string, arg2:string):Promise<string>;

export function SetTitle(arg1:string):Promise<void>;
