// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Evaluate(arg1:string):Promise<main.EvalResult>;

export function OpenFile():Promise<main.FileResult>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SetTitle(arg1:string):Promise<void>;
